### ISSUE TITLE
tailwind-primitives module missing

### ISSUE THREAD

**Issue by dink** [cwsdigital/cws-twill-base#1]
Hi!

Was just about take twill for a spin, but your node module `tailwind-primitives` is not available during install, and it errors out with the following:

```
...
npm ERR! command git ls-remote ssh://git@github.com/cwsdigital/tailwind-primitives.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```

Is there any way to fix this?

Thanks

**Comment by chrispymm** [comment]
Hi there, 
The tailwind primitives plugin is based on some proprietary code that is paid-for content, so it is a private GitHub repo just for our org.

You should just be able to remove this from the package.json and it should all still work fine. 

Please bear in kind this repo is an actively worked on WIP - it’s something I’m currently putting together as a project base for our agency - you’ll very-likely run into bugs at the moment. And I’m pretty certain the readme is out of date, and there’s not a whole lot of docs or code comments!!  

If you want an easier install it’s also now a packagist repository so you should be able to 

‘composer create-project cwsdigital/twill-base {your-project-name}’

**Comment by dink** [comment]
Thanks for the clarification -- I was able to get going without it.
